apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: nick
  sources:
    - repoURL: oci://docker.io/envoyproxy/gateway-helm
      chart: gateway-helm
      targetRevision: v1.6.1
      helm:
        skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true